/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          950: "var(--primary-950)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          950: "var(--secondary-950)",
        },
        tertiary: {
          50: "var(--tertiary-50)",
          100: "var(--tertiary-100)",
          200: "var(--tertiary-200)",
          300: "var(--tertiary-300)",
          400: "var(--tertiary-400)",
          500: "var(--tertiary-500)",
          600: "var(--tertiary-600)",
          700: "var(--tertiary-700)",
          800: "var(--tertiary-800)",
          900: "var(--tertiary-900)",
          950: "var(--tertiary-950)",
        },
        red: {
          50: "var(--red-50)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
          950: "var(--red-950)",
        },
        orange: {
          50: "var(--orange-50)",
          100: "var(--orange-100)",
          200: "var(--orange-200)",
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
          800: "var(--orange-800)",
          900: "var(--orange-900)",
          950: "var(--orange-950)",
        },
        green: {
          50: "var(--green-50)",
          100: "var(--green-100)",
          200: "var(--green-200)",
          300: "var(--green-300)",
          400: "var(--green-400)",
          500: "var(--green-500)",
          600: "var(--green-600)",
          700: "var(--green-700)",
          800: "var(--green-800)",
          900: "var(--green-900)",
          950: "var(--green-950)",
        },

        transparent: "var(--transparent)",

        background: {
          DEFAULT: "var(--background)",
          "level-1": "var(--background-level-1)",
          "level-2": "var(--background-level-2)",
          "level-3": "var(--background-level-3)",
          "level-4": "var(--background-level-4)",
          "level-5": "var(--background-level-5)",
        },
        text: {
          body: "var(--text-body)",
          minor: "var(--text-minor)",
          "accent-primary": "var(--text-accent-primary)",
          "accent-secondary": "var(--text-accent-secondary)",
          link: "var(--text-link)",
          "link-undeline": "var(--text-link-underline)",
        },

        input: {
          text: "var(--input-text)",
          primary: "var(--input-primary)",
          background: "var(--input-background)",
          border: "var(--input-border)",
          "border-focus": "var(--input-border-focus)",
          "mask-hover": "var(--input-mask-hover)",
        },

        button: {
          primary: {
            background: "var(--button-primary-background)",
            "background-hover": "var(--button-primary-background-hover)",
            text: "var(--button-primary-text)",
            "text-hover": "var(--button-primary-text-hover)",
          },
          secondary: {
            background: "var(--button-secondary-background)",
            "background-hover": "var(--button-secondary-background-hover)",
            text: "var(--button-secondary-text)",
            "text-hover": "var(--button-secondary-text-hover)",
          },

          tertiary: {
            background: "var(--button-tertiary-background)",
            "background-hover": "var(--button-tertiary-background-hover)",
            text: "var(--button-tertiary-text)",
            "text-hover": "var(--button-tertiary-text-hover)",
          },
          error: {
            background: "var(--button-error-background)",
            "background-hover": "var(--button-error-background-hover)",
            text: "var(--button-error-text)",
            "text-hover": "var(--button-error-text-hover)",
          },

          warning: {
            background: "var(--button-warning-background)",
            "background-hover": "var(--button-warning-background-hover)",
            text: "var(--button-warning-text)",
            "text-hover": "var(--button-warning-text-hover)",
          },

          success: {
            background: "var(--button-success-background)",
            "background-hover": "var(--button-success-background-hover)",
            text: "var(--button-success-text)",
            "text-hover": "var(--button-success-text-hover)",
          },
        },

        error: {
          background: "var(--error-background)",
          "background-hover": "var(--error-background-hover)",
          heading: "var(--error-heading)",
          text: "var(--error-text)",
          "text-minor": "var(--error-text-minor)",
          "text-hover": "var(--error-text-hover)",
          border: "var(--error-border)",
          "border-highlight": "var(--error-border-highlight)",
          "border-hover": "var(--error-border-hover)",
          "border-focus": "var(--error-border-focus)",
        },
        warning: {
          background: "var(--warning-background)",
          "background-hover": "var(--warning-background-hover)",
          heading: "var(--warning-heading)",
          text: "var(--warning-text)",
          "text-hover": "var(--warning-text-hover)",
          border: "var(--warning-border)",
          "border-hover": "var(--warning-border-hover)",
        },

        success: {
          background: "var(--success-background)",
          "background-hover": "var(--success-background-hover)",
          heading: "var(--success-heading)",
          text: "var(--success-text)",
          "text-hover": "var(--success-text-hover)",
          border: "var(--success-border)",
          "border-hover": "var(--success-border-hover)",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
